# Generated by Django 2.1.2 on 2018-10-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181029_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='uploaded_by_user',
        ),
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
